window.App.Flowdata.FIXTURES = [
 {
  "status": "Broken Down System", 
  "waterCommittee": "No", 
  "constructionDate": "2003", 
  "mainProblem": "Well polluted", 
  "photo": "http://flowliberia.s3.amazonaws.com/images/wfpPhoto296629573422.jpg", 
  "wPtype": "Handpump on hand-dug well", 
  "collectMoney": "", 
  "longitude": "-9.22230686", 
  "usedForDrinking": "No  abandoned", 
  "surveyDate": "03-02-2011 13:05:04 UTC", 
  "whoInstalled": "acf", 
  "hPtype": "Afridev", 
  "submitter": "user22", 
  "latitude": "6.95015193", 
  "settlement": "lowarta", 
  "quality": "Soft / Clean / Sweet", 
  "id": "942867", 
  "quantity": "Dry (permanently)"
 }, 
 {
  "status": "Broken Down System", 
  "waterCommittee": "Yes", 
  "constructionDate": "2007", 
  "mainProblem": "Well polluted", 
  "photo": "http://flowliberia.s3.amazonaws.com/images/wfpPhoto2122673971770.jpg", 
  "wPtype": "Handpump on hand-dug well", 
  "collectMoney": "Yes  monthly", 
  "longitude": "-10.57733352", 
  "usedForDrinking": "No  abandoned", 
  "surveyDate": "22-01-2011 08:13:06 UTC", 
  "whoInstalled": "ECHOGAA", 
  "hPtype": "Afridev", 
  "submitter": "user11", 
  "latitude": "7.26874674", 
  "settlement": "Ballah Bassa  Weasua Clan", 
  "quality": "", 
  "id": "956847", 
  "quantity": "Dry (permanently)"
 }, 
 {
  "status": "Broken Down System", 
  "waterCommittee": "Yes", 
  "constructionDate": "1997", 
  "mainProblem": "Well polluted", 
  "photo": "http://flowliberia.s3.amazonaws.com/images/wfpPhoto723025996815.jpg", 
  "wPtype": "Handpump on hand-dug well", 
  "collectMoney": "Never", 
  "longitude": "-9.35027855", 
  "usedForDrinking": "No  abandoned", 
  "surveyDate": "30-01-2011 18:12:03 UTC", 
  "whoInstalled": "IRC", 
  "hPtype": "Afridev", 
  "submitter": "user omega", 
  "latitude": "7.00874309", 
  "settlement": "Jinniepeleta Town", 
  "quality": "Colored: Brownish", 
  "id": "1123906", 
  "quantity": "Seasonal"
 }, 
 {
  "status": "Broken Down System", 
  "waterCommittee": "Yes", 
  "constructionDate": "2011", 
  "mainProblem": "Well polluted", 
  "photo": "http://flowliberia.s3.amazonaws.com/images/wfpPhoto379399425128.jpg", 
  "wPtype": "Handpump on hand-dug well", 
  "collectMoney": "Yes  monthly", 
  "longitude": "-9.47467774", 
  "usedForDrinking": "No  abandoned", 
  "surveyDate": "25-01-2011 10:29:22 UTC", 
  "whoInstalled": "ryc", 
  "hPtype": "India Mark", 
  "submitter": "user14", 
  "latitude": "7.00719572", 
  "settlement": "sopd", 
  "quality": "Soft / Clean / Sweet", 
  "id": "1048636", 
  "quantity": "Seasonal"
 }, 
 {
  "status": "Broken Down System", 
  "waterCommittee": "Yes", 
  "constructionDate": "2009", 
  "mainProblem": "Well polluted", 
  "photo": "http://flowliberia.s3.amazonaws.com/images/wfpPhoto2005056836862.jpg", 
  "wPtype": "Handpump on hand-dug well", 
  "collectMoney": "Yes  monthly", 
  "longitude": "-10.19116804", 
  "usedForDrinking": "No  abandoned", 
  "surveyDate": "11-02-2011 12:29:01 UTC", 
  "whoInstalled": "ICRC", 
  "hPtype": "Afridev", 
  "submitter": "user28", 
  "latitude": "8.12492751", 
  "settlement": "Kembalahun", 
  "quality": "Bad Smell or Taste", 
  "id": "981985", 
  "quantity": "Enough to meet needs year-round"
 }, 
 {
  "status": "Broken Down System", 
  "waterCommittee": "Yes", 
  "constructionDate": "2003", 
  "mainProblem": "Well polluted", 
  "photo": "http://flowliberia.s3.amazonaws.com/images/wfpPhoto1867955436755.jpg", 
  "wPtype": "Handpump on hand-dug well", 
  "collectMoney": "Never", 
  "longitude": "-10.1799054", 
  "usedForDrinking": "No  abandoned", 
  "surveyDate": "28-01-2011 14:15:37 UTC", 
  "whoInstalled": "zoa", 
  "hPtype": "Afridev", 
  "submitter": "user24", 
  "latitude": "6.67324933", 
  "settlement": "massaquoi  town", 
  "quality": "close to   cementa ry|close to   cementa ry", 
  "id": "997147", 
  "quantity": "Seasonal"
 }, 
 {
  "status": "Broken Down System", 
  "waterCommittee": "No", 
  "constructionDate": "1985", 
  "mainProblem": "Well polluted", 
  "photo": "http://flowliberia.s3.amazonaws.com/images/wfpPhoto342101843418.jpg", 
  "wPtype": "Handpump on hand-dug well", 
  "collectMoney": "", 
  "longitude": "-9.46043336", 
  "usedForDrinking": "No  abandoned", 
  "surveyDate": "31-01-2011 12:40:12 UTC", 
  "whoInstalled": "bcadp", 
  "hPtype": "Afridev", 
  "submitter": "user22", 
  "latitude": "6.74472152", 
  "settlement": "gbnequelleh", 
  "quality": "Soft / Clean / Sweet", 
  "id": "1126916", 
  "quantity": "Seasonal"
 }, 
 {
  "status": "Broken Down System", 
  "waterCommittee": "Yes", 
  "constructionDate": "2007", 
  "mainProblem": "Well polluted", 
  "photo": "http://flowliberia.s3.amazonaws.com/images/wfpPhoto455921233410.jpg", 
  "wPtype": "Handpump on hand-dug well", 
  "collectMoney": "Yes  monthly", 
  "longitude": "-9.38607414", 
  "usedForDrinking": "No  abandoned", 
  "surveyDate": "08-02-2011 09:51:20 UTC", 
  "whoInstalled": "arc", 
  "hPtype": "Afridev", 
  "submitter": "user 10", 
  "latitude": "7.71582546", 
  "settlement": "kpaiyea", 
  "quality": "Soft / Clean / Sweet", 
  "id": "1124861", 
  "quantity": "Seasonal"
 }, 
 {
  "status": "Broken Down System", 
  "waterCommittee": "No", 
  "constructionDate": "2000", 
  "mainProblem": "Well polluted", 
  "photo": "http://flowliberia.s3.amazonaws.com/images/wfpPhoto462517571742.jpg", 
  "wPtype": "Handpump on hand-dug well", 
  "collectMoney": "", 
  "longitude": "-8.93097311", 
  "usedForDrinking": "No  abandoned", 
  "surveyDate": "03-02-2011 14:27:05 UTC", 
  "whoInstalled": "africare", 
  "hPtype": "Afridev", 
  "submitter": "user29", 
  "latitude": "7.11080859", 
  "settlement": "blohn", 
  "quality": "Colored: Brownish", 
  "id": "1068555", 
  "quantity": "Dry (permanently)"
 }, 
 {
  "status": "Broken Down System", 
  "waterCommittee": "Yes", 
  "constructionDate": "2007", 
  "mainProblem": "Well polluted", 
  "photo": "http://flowliberia.s3.amazonaws.com/images/wfpPhoto1462546888494.jpg", 
  "wPtype": "Handpump on hand-dug well", 
  "collectMoney": "Yes  monthly", 
  "longitude": "-9.0436014", 
  "usedForDrinking": "No  abandoned", 
  "surveyDate": "06-02-2011 16:54:31 UTC", 
  "whoInstalled": "TEAR Fund", 
  "hPtype": "Afridev", 
  "submitter": "user35", 
  "latitude": "6.00294747", 
  "settlement": "Dorgboe Town", 
  "quality": "Milky", 
  "id": "1048890", 
  "quantity": "Dry (permanently)"
 }
]
